#include QMK_KEYBOARD_H

/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

enum layers {
    _QWERTY,
    _LOWER,
    _RAISE,
    _ADJUST,
};

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    /* QWERTY
     * ,-----------------------------------------.                    ,-----------------------------------------.
     * | ESC  |   1  |   2  |   3  |   4  |   5  |                    |   6  |   7  |   8  |   9  |   0  |  =   |
     * |------+------+------+------+------+------|                    |------+------+------+------+------+------|
     * | Tab  |   Q  |  W   |  E   |   R  |   T  |                    |   Y  |   U  |   I  |   O  |   P  |  -   |
     * |------+------+------+------+------+------|                    |------+------+------+------+------+------|
     * |LShift|lsft A|lctl S|lalt D|lgui F|   G  |-------.    ,-------|   H  |rgui J|ralt K|rctl L|rsft ;|  '   |
     * |------+------+------+------+------+------|   [   |    |    ]  |------+------+------+------+------+------|
     * |LCTRL |   Z  |   X  |   C  |   V  |   B  |-------|    |-------|   N  |   M  |   ,  |   .  |   /  |RShift|
     * `-----------------------------------------/       /     \      \-----------------------------------------'
     *                   |      |      | L1   | / L3    /       \L4    \  |   L2  |      |      |
     *                   |      |      |      |/ Space /         \Enter \ | Backsp|      |      |
     *                   `----------------------------'           '------''--------------------'
     */
    [_QWERTY] = LAYOUT( \
    KC_ESC,  KC_1, KC_2, KC_3, KC_4, KC_5,                           KC_6, KC_7, KC_8, KC_9, KC_0, KC_EQL, \
    KC_TAB,  KC_Q, KC_W, KC_E, KC_R, KC_T,                           KC_Y, KC_U, KC_I, KC_O, KC_P, KC_MINS, \
    KC_LCTL, LSFT_T(KC_A), LCTL_T(KC_S), LALT_T(KC_D), LGUI_T(KC_F), KC_G, KC_H, RGUI_T(KC_J), RALT_T(KC_K), RCTL_T(KC_L), RSFT_T( KC_SCLN), KC_QUOT, \
    KC_LSFT, KC_Z, KC_X, KC_C, KC_V, KC_B,     KC_LBRC,   KC_RBRC,  KC_N, KC_M, KC_COMM, KC_DOT, KC_SLSH, KC_RSFT, \
                    KC_LALT, KC_LGUI, KC_TAB, LT(1, KC_SPC),        LT(2, KC_ENT), KC_BSPC, MO(2), KC_LCTL),
                    KC_TRNS, KC_TRNS, MO(1), LT(3,KC_SPC),          KC_ENT, LT(2,KC_BSPC), KC_TRNS, KC_TRNS),
    /* LOWER
     * ,-----------------------------------------.                    ,-----------------------------------------.
     * |      |      |      |      |      |      |                    |      |      |      |      |      |      |
     * |------+------+------+------+------+------|                    |------+------+------+------+------+------|
     * |      |   1  |   2  |   3  |   4  |   5  |                    |   6  |   7  |   8  |   9  |   0  |      |
     * |------+------+------+------+------+------|                    |------+------+------+------+------+------|
     * |LShift|   !  |   @  |   #  |   $  |   %  |-------.    .-------| left | down |  up  | right| HOME | End  |
     * |------+------+------+------+------+------|       |    |   \   |------+------+------+------+------+------|
     * |LCTRL |      |      |      |      |      |-------|    |-------|   `  |   =  |   -  |  '   |   /  |RShift|
     * `-----------------------------------------/       /     \      \-----------------------------------------'
     *                   | LAlt | LGUI | LOWER| /Space  /       \lang  \  |lang  |ADJUST| RGUI |
     *                   |      |      |      |/       /         \      \ |      |      |      |
     *                   `----------------------------'           '------''--------------------'
     *
     */
    [_LOWER] = LAYOUT( \
    KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,                           KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, \
    KC_NO, KC_1, KC_2, KC_3, KC_4, KC_5,                                            KC_6, KC_7, KC_8, KC_9, KC_0, KC_NO, \
    KC_LCTL, KC_EXLM, KC_AT, KC_HASH, KC_DLR, KC_PERC,                              KC_LEFT, KC_DOWN, KC_UP, KC_RGHT, KC_HOME, KC_END, \
    KC_LSFT, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,KC_TRNS, KC_TRNS,     KC_BSLS,      KC_GRV, KC_EQL, KC_MINS, KC_QUOT, KC_SLSH, KC_RSFT, \
                    KC_LALT, KC_LGUI, KC_TRNS,      KC_SPC,             LCMD(KC_SPC),     LCMD(KC_SPC), MO(3), KC_DEL),
    /* RAISE
     * ,-----------------------------------------.                    ,-----------------------------------------.
     * |      |      |      |      |      |      |                    |      |      |      |      |      |      |
     * |------+------+------+------+------+------|                    |------+------+------+------+------+------|
     * |      | Play | Vol+ |      |      |      |                    |      |      |      |      |      |      |
     * |------+------+------+------+------+------|                    |------+------+------+------+------+------|
     * |LShift| Prev | Vol- | Next |      |      |-------.    ,-------|      |      |      |      |      |      |
     * |------+------+------+------+------+------|       |    |       |------+------+------+------+------+------|
     * |LCTRL | Mute |      |      |      |      |-------|    |-------|      |   _  |   +  |   {  |   }  |RShift|
     * `-----------------------------------------/       /     \      \-----------------------------------------'
     *                   | LAlt | LGUI | LOWER| /Space  /       \Enter \  |Backsp|      | RGUI |
     *                   |      |      |      |/       /         \      \ |      |      |      |
     *                   `----------------------------'           '------''--------------------'
     */
    [_RAISE] = LAYOUT( \
    KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,                    KC_TRNS, KC_TRNS,  KC_TRNS,  KC_TRNS, KC_TRNS, KC_TRNS, \
    KC_GRV, KC_MPLY, KC__VOLUP, KC_F4, KC_F5, KC_F6,                         KC_F1,   KC_F2,    KC_F3,    KC_F4,   KC_F5,   KC_NO,\
    KC_LCTL, KC_MRWD, KC__VOLDOWN, KC_MFFD, KC_F5, KC_F6,                    KC_F6,   KC_F7,    KC_F8,    KC_F9,   KC_F10,  KC_NO, \
    KC_LSFT, KC__MUTE, KC_F9, KC_F10, KC_F11, KC_F12,     KC_TRNS, KC_TRNS,  KC_BTN1, KC_BTN2,  KC_BTN3,  KC_F11,  KC_F12,  KC_RSFT, \
                    KC_LALT, KC_LGUI, KC_TRNS, KC_SPC,               KC_ENT, KC_BSPC, KC_TRNS,  KC_RGUI),

    [_ADJUST] = LAYOUT(KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS)};

layer_state_t layer_state_set_user(layer_state_t state) {
    state = update_tri_layer_state(state, _RAISE, _LOWER, _ADJUST);
    return state;
}

//SSD1360 OLED update loop, make sure to enable OLED_ENABLE=yes in rules.mk
#ifdef OLED_ENABLE

oled_rotation_t oled_init_user(oled_rotation_t rotation) {
  if (!is_keyboard_master())
    return OLED_ROTATION_180;  // flips the display 180 degrees if offhand
  return rotation;
}

// When you add source files to SRC in rules.mk, you can use functions.
const char *read_layer_state(void);
const char *read_logo(void);
void set_keylog(uint16_t keycode, keyrecord_t *record);
const char *read_keylog(void);
const char *read_keylogs(void);

// const char *read_mode_icon(bool swap);
// const char *read_host_led_state(void);
// void set_timelog(void);
// const char *read_timelog(void);

bool oled_task_user(void) {
  if (is_keyboard_master()) {
    // If you want to change the display of OLED, you need to change here
    oled_write_ln(read_layer_state(), false);
    oled_write_ln(read_keylog(), false);
    oled_write_ln(read_keylogs(), false);
    //oled_write_ln(read_mode_icon(keymap_config.swap_lalt_lgui), false);
    //oled_write_ln(read_host_led_state(), false);
    //oled_write_ln(read_timelog(), false);
  } else {
    oled_write(read_logo(), false);
  }
    return false;
}
#endif // OLED_ENABLE

bool process_record_user(uint16_t keycode, keyrecord_t *record) {
  if (record->event.pressed) {
#ifdef OLED_ENABLE
    set_keylog(keycode, record);
#endif
    // set_timelog();
  }
  return true;
}

