#include QMK_KEYBOARD_H

/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
  [0] = LAYOUT(\
    KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,                                 KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,\
    KC_TRNS, KC_Q, KC_W, KC_E, KC_R, KC_T,                                                KC_Y, KC_U, KC_I, KC_O, KC_P, KC_TRNS,\
    KC_TRNS, LSFT_T(KC_A), LCTL_T(KC_S), LALT_T(KC_D), LGUI_T(KC_F), KC_G,                KC_H, RGUI_T(KC_J), RALT_T(KC_K), RCTL_T(KC_L), RSFT_T(KC_SCLN), KC_TRNS,\
    KC_TRNS, KC_Z, KC_X, KC_C, KC_V, KC_B, KC_TRNS,                                       KC_TRNS, KC_N, KC_M, KC_COMM, KC_DOT, KC_SLSH, KC_TRNS,\
    KC_TRNS, KC_TRNS, TG(1), LT(3,KC_SPC),                                        KC_ENT, LT(2,KC_BSPC), KC_TRNS, KC_TRNS),
    /* KC_TRNS, KC_TRNS, LT(1, KC_TAB), LT(3,KC_SPC),                                        KC_ENT, LT(2,KC_BSPC), KC_TRNS, KC_TRNS), */
  [1] = LAYOUT(\
    KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,                                 KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,\
    KC_TRNS, KC_1, KC_2, KC_3, KC_4, KC_5,                                                KC_6, KC_7, KC_8, KC_9, KC_0, KC_TRNS,\
    KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,                                 KC_LEFT, KC_DOWN, KC_UP, KC_RGHT, KC_TRNS, KC_TRNS,\
    KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,                        KC_TRNS, KC_MINS, KC_EQL, KC_LBRC, KC_RBRC, KC_QUOT, KC_TRNS,\
    KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,                                                   KC_ENT, KC_BSPC, KC_TRNS, KC_TRNS),
  [2] = LAYOUT(\
    KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,                                 KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,\
    KC_TRNS, KC_MPLY, KC__VOLUP, KC_GRV, KC_BSLS, KC_TRNS,                                KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,\
    KC_TRNS, KC_TAB, KC__VOLDOWN, KC_MFFD, KC_ESC, KC_TRNS,                             KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,\
    /* KC_TRNS, KC_MRWD, KC__VOLDOWN, KC_MFFD, KC_ESC, KC_TRNS,                             KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,\ */
    KC_TRNS, KC__MUTE, KC_TRNS, KC_CAPS, KC_ESC, KC_TRNS, KC_TRNS,                        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,\
    KC_TRNS, KC_TRNS, KC_TAB, KC_SPC,                                                     KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS),
  [3] = LAYOUT(\
    KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,                                 KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
    KC_TRNS, KC_F1, KC_F2, KC_F3, KC_F4, KC_F5,                                           KC_F6, KC_F7, KC_F8, KC_F9, KC_F10, KC_TRNS,
    KC_TRNS, KC_TRNS, KC_TRNS, KC_F11, KC_F12, KC_TRNS,                                   KC_LEFT, KC_DOWN, KC_UP, KC_RGHT, KC_TRNS, KC_TRNS,
    KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,                        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
    KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,                                                   LGUI(KC_SPC), LGUI(KC_SPC), KC_TRNS, KC_TRNS)
};

